version: 2.1

jobs:
  build_docker:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install
      - setup_remote_docker:
          version: default
      - run: 
          name: Build Docker Image
          command: |
            echo "Building images ..........."
            
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed asukakazama/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user asukakazama/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend asukakazama/udagram-frontend:v1

            docker build -t reverseproxy ./reverseproxy
            docker tag reverseproxy asukakazama/reverseproxy:v1

            echo "Build successfully !"
      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo "Pushing images ..........."

            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

            docker push asukakazama/udagram-api-user:v1
            docker push asukakazama/udagram-api-feed:v1
            docker push asukakazama/udagram-frontend:v1
            docker push asukakazama/reverseproxy:v1

            echo "Push successfully !"

workflows:
  default:
    jobs:
      - build_docker