apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: asukakazama/udagram-api-user:v1
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapRef:
                  name: env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapRef:
                  name: env-config
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                configMapRef:
                  name: env-config
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapRef:
                  name: env-config
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom:
                configMapRef:
                  name: env-config
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapRef:
                  name: env-config
                  key: URL
          volumeMounts:
            - name: asukakazama-secret
              mountPath: "/root/.aws/"
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      volumes:
        - name: asukakazama-secret
          secret:
            secretName: aws-secret
