apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asukakazama/udagram-frontend:v3
          ports:
            - containerPort: 8100
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
